interface UnitLabels {
  meter: Resource
  kilometer: Resource
  mile: Resource
  foot: Resource
  inch: Resource
  gram: Resource
  kilogram: Resource
  pound: Resource
  celsius: Resource
  kelvin: Resource
  fahrenheit: Resource
  liter: Resource
  gallon_us: Resource
  gallon_uk: Resource
  pascal: Resource
  bar: Resource
  psi: Resource
}

export const unitLabels: UnitLabels = {
  meter: $r('app.string.unit_meter'),
  kilometer: $r('app.string.unit_kilometer'),
  mile: $r('app.string.unit_mile'),
  foot: $r('app.string.unit_foot'),
  inch: $r('app.string.unit_inch'),
  gram: $r('app.string.unit_gram'),
  kilogram: $r('app.string.unit_kilogram'),
  pound: $r('app.string.unit_pound'),
  celsius: $r('app.string.unit_celsius'),
  kelvin: $r('app.string.unit_kelvin'),
  fahrenheit: $r('app.string.unit_fahrenheit'),
  liter: $r('app.string.unit_liter'),
  gallon_us: $r('app.string.unit_gallon_us'),
  gallon_uk: $r('app.string.unit_gallon_uk'),
  pascal: $r('app.string.unit_pascal'),
  bar: $r('app.string.unit_bar'),
  psi: $r('app.string.unit_psi')
};